### ISSUE TITLE
page required to be reloaded after rendering of video completes.

### ISSUE THREAD

**Issue by indianquant** [mohtamohit/Videofy#1]
The webpage requires to be refreshed after the rendering completes in the console.

**Comment by surya-veer** [comment]
Thanks, @priyanshuvarsh,
I have fixed this issue.
Check this commit 
https://github.com/mohtamohit/Videofy/commit/1361c4ed6d0aa02a0307615fcfae8ba345df32ac

**Comment by indianquant** [comment]
Thanks a lot for the fast reply.
