### ISSUE TITLE
Videofy Logo is missing

### ISSUE THREAD

**Issue by mohtamohit** [mohtamohit/Videofy#7]
This link -> https://github.com/mohtamohit/Videofy/blob/master/videofy.png?raw=true is not working. It was to display logo on readme.

**Comment by indianquant** [comment]
Hello Sir,
Thanks for pointing it out. I will update in in the next patch. :P

**Comment by surya-veer** [comment]
[FIXED] 
This is because of the **videofy.png** changed to **logo.png** and path.
Thanks @priyanshuvarsh
